### ISSUE TITLE
KeyError after random choice of cluster in l.815

### ISSUE THREAD

**Issue by g-schlake** [PhilJahn/DENSIRED#1]
Hello,

I am currently using Densired to generate a number of datasets. 
I sometimes get an KeyError in my versions equivalent of line 817 in Datagen. I suppose, that this is due to the random choice of cluid is made on the range of the length of self.cores.keys() instead of on the actual elements. At least in my case, I have clusters with negative numbers as keys, leading to the size of keys being bigger than the largest key and illegal elements selected. These are the parameters for my Skeleton ({'clunum': 3, 'connections': 4, 'dim': 2, 'min_dist': 0.5, 'ratio_noise': 0.0, 'safety':False}) and for generate data ({'data_num': 500}). The cores than have the keys [0,1,2,-2], whereas in case of the error, 3 is selected. In my version (installed via pip) these are lines 758 to 760.

Best regards and thanks for you work,
Georg

**Comment by PhilJahn** [comment]
Thank you, I'm sorry I took so long to answer. It has been fixed as you described (along with other side effects of the presence of connection cores) on this repository. I will update the pip version later today.
